# Generated by Django 4.2 on 2023-04-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('eng_name', models.CharField(default=models.CharField(max_length=250), max_length=250)),
                ('description', models.CharField(max_length=400, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('coverUrl', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('eng_name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('title_eng', models.CharField(default=models.CharField(max_length=250), max_length=250)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('pdfFileUrl', models.CharField(max_length=250)),
                ('coverUrl', models.CharField(max_length=250)),
                ('authors', models.ManyToManyField(related_name='books', to='bookstore.author')),
                ('categories', models.ManyToManyField(related_name='books', to='bookstore.category')),
            ],
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='bookstore_b_title_92b564_idx'),
        ),
    ]
