# Generated by Django 4.2 on 2023-04-26 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_remove_author_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
