# Generated by Django 4.2 on 2023-04-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_author_eng_name_book_title_eng_category_eng_name_and_more'),
        ('user', '0002_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, to='bookstore.book'),
        ),
    ]
